# Generated by Django 2.0.13 on 2019-05-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20190509_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangementmapcomponent',
            name='map',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='maps.ArrangementMap'),
            preserve_default=False,
        ),
    ]
