# Generated by Django 2.0.13 on 2019-05-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_arrangementmapcomponent_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangementmapcomponent',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
