# Generated by Django 2.0.13 on 2019-05-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_arrangementmapcomponent_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangementmapcomponent',
            name='publish',
        ),
        migrations.AddField(
            model_name='arrangementmap',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
