# Generated by Django 2.0.13 on 2019-05-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20190510_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedArrangementMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.IntegerField()),
                ('deleted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
