# Generated by Django 2.0.13 on 2019-05-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_deletedarrangementmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedarrangementmap',
            name='primary_key',
        ),
        migrations.AddField(
            model_name='deletedarrangementmap',
            name='ref',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
