version: '3'

services:
  cartographer-db:
    image: postgres:10.4
    volumes:
      - cartographerdbvolume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cartographer_backend
      - POSTGRES_PASSWORD=cartographer_backend
      - POSTGRES_DB=cartographer_backend_dev
  cartographer-backend:
    build: ./cartographer_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cartographer_backend:/code/cartographer_backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - cartographer-db
  cartographer-frontend:
    build: ./cartographer_frontend
    command: ["yarn", "start"]
    volumes:
      - ./cartographer_frontend:/code/cartographer_frontend
      - node-modules:/code/cartographer_frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  cartographerdbvolume:
  node-modules:
