version: '2.4'

services:
  cartographer-db:
    image: postgres:10.4
    volumes:
      - cartographerdbvolume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev.db
  cartographer-backend:
    image: rockarch/cartographer_backend:0.7
    command: apachectl -D FOREGROUND
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - cartographer-db
  cartographer-frontend:
    image: rockarch/cartographer_frontend:0.6
    ports:
      - "3000:80"
    depends_on:
      - cartographer-backend

volumes:
  cartographerdbvolume:
    driver: vsphere
