version: '2.4'

services:
  cartographer-backend:
    image: rockarch/cartographer_backend:latest
    command: apachectl -D FOREGROUND
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
  cartographer-frontend:
    image: rockarch/cartographer_frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - cartographer-backend
