version: '2.4'

services:
  cartographer-db:
    image: postgres:10.4
    volumes:
      - cartographerdbvolume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev.db
  cartographer-backend:
    image: rockarch/cartographer_backend:0.5
    command: gunicorn cartographer_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/cartographer_backend/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - cartographer-db
  cartographer-frontend:
    image: rockarch/cartographer_frontend:0.4
    ports:
      - "3000:80"
    depends_on:
      - cartographer-backend
  nginx:
    image: rockarch/django_nginx:latest
    ports:
      - "8001:8001"
    volumes:
      - static_volume:/code/nginx/static/
    depends_on:
      - cartographer-backend
    env_file:
      - ./.env.dev.nginx

volumes:
  cartographerdbvolume:
    driver: vsphere
  static_volume:
    driver: vsphere
