version: '2.4'

services:
  cartographer-backend:
    image: rockarch/cartographer_backend:0.4
    command: gunicorn cartographer_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/cartographer_backend/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - cartographer-db
  cartographer-frontend:
    image: rockarch/cartographer_frontend:0.3
    ports:
      - "3000:80"
    depends_on:
      - cartographer-backend
  nginx:
    image: rockarch/django_nginx:latest
    ports:
      - "8001:8001"
    volumes:
      - static_volume:/code/nginx/static/
    depends_on:
      - cartographer-backend
    env_file:
      - ./.env.prod.nginx


volumes:
  cartographerdbvolume:
    driver: vsphere
  static_volume:
    driver: vsphere
