version: '2.4'

services:
  cartographer-db:
    image: postgres:10.4
    volumes:
      - cartographerdbvolume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod.db
  cartographer-backend:
    image: rockarch/cartographer_backend:latest
    command: gunicorn cartographer_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - cartographer-db
  cartographer-frontend:
    image: rockarch/cartographer_frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - cartographer-backend

volumes:
  cartographerdbvolume:
    driver: vsphere
  static_volume:
    driver: vsphere
